template<typename PointT>
std::pair<typename pcl::PointCloud<PointT>::Ptr, typename pcl::PointCloud<PointT>::Ptr>
ProcessPointClouds<PointT>::SegmentPlaneGPU(typename pcl::PointCloud<PointT>::Ptr cloud,
                                             int maxIterations, float distanceThreshold)
{
    // 1. Flatten the point cloud (x, y, z) into a continuous array.
    std::vector<float>* h_points = new std::vector<float>();
    for (size_t i = 0; i < cloud->points.size(); ++i) {
        h_points->push_back(cloud->points[i].x);
        h_points->push_back(cloud->points[i].y);
        h_points->push_back(cloud->points[i].z);
    }
    const int numPoints = cloud->points.size();

    // 2. OpenCL setup: platform, device, context, and command queue.
    cl_platform_id platform;
    clGetPlatformIDs(1, &platform, NULL);
    cl_device_id device;
    clGetDeviceIDs(platform, CL_DEVICE_TYPE_GPU, 1, &device, NULL);
    cl_context context = clCreateContext(NULL, 1, &device, NULL, NULL, NULL);
    // Create command queue with profiling enabled.
    cl_command_queue queue = clCreateCommandQueue(context, device, CL_QUEUE_PROFILING_ENABLE, NULL);

    // 3. Load and build the batched kernel.
    const char* kernel_filename = "../src/ransac_kernel.cl";
    std::string kernel_source = loadKernel(kernel_filename);
    const char* kernel_source_cstr = kernel_source.c_str();
    cl_program program = clCreateProgramWithSource(context, 1, &kernel_source_cstr, NULL, NULL);
    if (clBuildProgram(program, 1, &device, NULL, NULL, NULL) != CL_SUCCESS) {
        size_t log_size;
        clGetProgramBuildInfo(program, device, CL_PROGRAM_BUILD_LOG, 0, NULL, &log_size);
        std::vector<char> build_log(log_size);
        clGetProgramBuildInfo(program, device, CL_PROGRAM_BUILD_LOG, log_size, build_log.data(), NULL);
        std::cerr << "Error building OpenCL program:" << std::endl
                  << build_log.data() << std::endl;
        exit(1);
    }
    cl_kernel kernel = clCreateKernel(program, "batched_ransac_plane_segmentation", NULL);

    // 4. Create buffers:
    // 4a. Buffer for the flattened point cloud.
    size_t pointsBufferSize = numPoints * 3 * sizeof(float);
    cl_mem d_points_buffer = clCreateBuffer(context, CL_MEM_READ_ONLY, pointsBufferSize, NULL, NULL);
    clEnqueueWriteBuffer(queue, d_points_buffer, CL_TRUE, 0, pointsBufferSize, h_points->data(), 0, NULL, NULL);

    // 4b. Buffer for the candidate plane parameters.
    // Each candidate has 5 floats: [A, B, C, D, normFactor]
    size_t numCandidates = maxIterations;
    size_t candidatesBufferSize = numCandidates * 5 * sizeof(float);
    cl_mem d_candidates_buffer = clCreateBuffer(context, CL_MEM_READ_ONLY, candidatesBufferSize, NULL, NULL);

    // 4c. Buffer for the candidate inlier counts.
    size_t candidateCountsBufferSize = numCandidates * sizeof(int);
    cl_mem d_candidateCounts = clCreateBuffer(context, CL_MEM_WRITE_ONLY, candidateCountsBufferSize, NULL, NULL);

    // 5. Generate candidate plane parameters in batch (on the host).
    // Each candidate is generated by choosing 3 random points from the cloud.
    std::vector<float> candidatePlanes;
    candidatePlanes.reserve(numCandidates * 5);
    srand(time(NULL));
    for (int i = 0; i < numCandidates; i++) {
        int p1_id = (rand() % numPoints) * 3;
        int p2_id = (rand() % numPoints) * 3;
        int p3_id = (rand() % numPoints) * 3;

        float p1_x = h_points->at(p1_id);
        float p1_y = h_points->at(p1_id + 1);
        float p1_z = h_points->at(p1_id + 2);
        float p2_x = h_points->at(p2_id);
        float p2_y = h_points->at(p2_id + 1);
        float p2_z = h_points->at(p2_id + 2);
        float p3_x = h_points->at(p3_id);
        float p3_y = h_points->at(p3_id + 1);
        float p3_z = h_points->at(p3_id + 2);

        // Compute plane coefficients: A, B, C, D for plane Ax+By+Cz+D = 0.
        float A = (p2_y - p1_y) * (p3_z - p1_z) - (p2_z - p1_z) * (p3_y - p1_y);
        float B = (p2_z - p1_z) * (p3_x - p1_x) - (p2_x - p1_x) * (p3_z - p1_z);
        float C = (p2_x - p1_x) * (p3_y - p1_y) - (p2_y - p1_y) * (p3_x - p1_x);
        float D = -1.0f * (A * p1_x + B * p1_y + C * p1_z);
        float normFactor = sqrt(A * A + B * B + C * C);
        // If normFactor is 0 then skip candidate (rare, but can happen).
        if (fabs(normFactor) < 1e-6) {
            i--;
            continue;
        }
        candidatePlanes.push_back(A);
        candidatePlanes.push_back(B);
        candidatePlanes.push_back(C);
        candidatePlanes.push_back(D);
        candidatePlanes.push_back(normFactor);
    }
    // Write candidate plane parameters to device.
    clEnqueueWriteBuffer(queue, d_candidates_buffer, CL_TRUE, 0, candidatesBufferSize, candidatePlanes.data(), 0, NULL, NULL);

    // 6. Set kernel arguments.
    // We'll use a 2D NDRange: first dimension = numCandidates, second = numPoints.
    // In each candidate, we perform a parallel reduction of inlier flags.
    int arg = 0;
    clSetKernelArg(kernel, arg++, sizeof(cl_mem), &d_points_buffer);
    clSetKernelArg(kernel, arg++, sizeof(cl_mem), &d_candidates_buffer);
    clSetKernelArg(kernel, arg++, sizeof(int), &numPoints);
    clSetKernelArg(kernel, arg++, sizeof(float), &distanceThreshold);
    clSetKernelArg(kernel, arg++, sizeof(cl_mem), &d_candidateCounts);
    // The kernel will use local memory to accumulate inlier counts per candidate.
    // We set the local memory size to (local_work_size_y * sizeof(int)).
    // (This argument is set inside the kernel when we use 'extern __local int localSum[]'; see the kernel code below.)

    // 7. Launch the kernel.
    // Define the NDRange dimensions.
    // global_work_size[0]: candidate dimension, global_work_size[1]: point dimension.
    size_t global_work_size[2] = { numCandidates, (size_t)numPoints };
    // Choose a local work size on the second dimension.
    // (Assuming the candidate dimension remains 1 work-item per candidate in the candidate dimension.)
    size_t local_work_size[2] = { 1, 256 }; // Adjust 256 as appropriate (must divide numPoints or pad accordingly).

    auto startTime = std::chrono::steady_clock::now();
    clEnqueueNDRangeKernel(queue, kernel, 2, NULL, global_work_size, local_work_size, 0, NULL, NULL);
    clFinish(queue);

    // 8. Read back candidate inlier counts.
    std::vector<int> candidateCounts(numCandidates, 0);
    clEnqueueReadBuffer(queue, d_candidateCounts, CL_TRUE, 0, candidateCountsBufferSize, candidateCounts.data(), 0, NULL, NULL);

    // 9. Find the candidate with the maximum inlier count.
    int bestCandidateIdx = -1;
    int bestCount = 0;
    for (int i = 0; i < numCandidates; ++i) {
        if (candidateCounts[i] > bestCount) {
            bestCount = candidateCounts[i];
            bestCandidateIdx = i;
        }
    }

    if (bestCandidateIdx == -1) {
        std::cerr << "Could not estimate a planar model for the given dataset." << std::endl;
        // Cleanup and return original cloud separated into empty pair.
        delete h_points;
        return std::make_pair(cloud, typename pcl::PointCloud<PointT>::Ptr(new pcl::PointCloud<PointT>()));

    }

    // Retrieve the best candidate's parameters.
    int bestOffset = bestCandidateIdx * 5;
    float bestA = candidatePlanes[bestOffset + 0];
    float bestB = candidatePlanes[bestOffset + 1];
    float bestC = candidatePlanes[bestOffset + 2];
    float bestD = candidatePlanes[bestOffset + 3];
    float bestNormFactor = candidatePlanes[bestOffset + 4];

    // 10. (Optional) Re-compute inlier indices on the host using the best candidate parameters.
    pcl::PointIndices::Ptr bestInliers(new pcl::PointIndices());
    for (int i = 0; i < numPoints; i++) {
        float x = h_points->at(i * 3);
        float y = h_points->at(i * 3 + 1);
        float z = h_points->at(i * 3 + 2);
        float dist = fabs(bestA * x + bestB * y + bestC * z + bestD) / bestNormFactor;
        if (dist <= distanceThreshold) {
            bestInliers->indices.push_back(i);
        }
    }

    auto endTime = std::chrono::steady_clock::now();
    auto elapsedTime = std::chrono::duration_cast<std::chrono::milliseconds>(endTime - startTime);
    std::cout << "Batched plane segmentation took " << elapsedTime.count() << " milliseconds" << std::endl;

    // 11. Separate the cloud using the best inlier indices.
    std::pair<typename pcl::PointCloud<PointT>::Ptr, typename pcl::PointCloud<PointT>::Ptr> segResult = SeparateClouds(bestInliers, cloud);

    // Cleanup OpenCL resources.
    clReleaseMemObject(d_points_buffer);
    clReleaseMemObject(d_candidates_buffer);
    clReleaseMemObject(d_candidateCounts);
    clReleaseKernel(kernel);
    clReleaseProgram(program);
    clReleaseCommandQueue(queue);
    clReleaseContext(context);
    delete h_points;

    return segResult;
}